name: Jchiatt
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2678
title: J.C. Hiatt
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#898989'
    - '#211311'
    - '#7d5c52'
    - '#d59889'
    - '#cfd2d7'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0
  rhythmicContrast: 0.9485125548671931
purpose: []
